/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jy_sopt_gifexample_NDK */

#ifndef _Included_jy_sopt_gifexample_NDK
#define _Included_jy_sopt_gifexample_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jy_sopt_gifexample_NDK
 * Method:    getNDKTestString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jy_sopt_gifexample_NDK_getNDKTestString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
